# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [26]:
# Tu respuesta aquí
nombre = "Carolina"
edad = 38
print(f"Hola, me llamo {nombre} y tengo {edad} años.")

Hola, me llamo Carolina y tengo 38 años.


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [27]:
numeros = [10, 25, 3, 47, 8, 15]

# Tu respuesta aquí

# Imprime el primer y el último elemento.
print("Primer elemento:", numeros[0])
print("Último elemento:", numeros[-1])


Primer elemento: 10
Último elemento: 15


In [28]:
#Imprime los tres primeros elementos usando slicing
print("Tres primeros elementos:", numeros[:3])

Tres primeros elementos: [10, 25, 3]


In [29]:
#Agrega el número 99 al final de la lista
numeros.append(99)
print("Lista actualizada:", numeros)

Lista actualizada: [10, 25, 3, 47, 8, 15, 99]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [30]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

# Tu respuesta aquí
if estudiante["promedio"] >= 6:
    print("Aprobado")
else:
    print("Reprobado")

Aprobado


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [31]:
# Tu respuesta aquí
def calcular_area(base, altura):
    return base * altura / 2

# Llamada a la función
resultado = calcular_area(5, 8)

print("El área del triángulo:", resultado)

El área del triángulo: 20.0


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [32]:
# Tu respuesta aquí
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
out = [item**2 for item in x]
out

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

---
## Parte 2 — NumPy

In [33]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [34]:
# Tu respuesta aquí

# arreglo
arreglo = [1.5, 2.5, 3.5, 4.5]
arreglo

[1.5, 2.5, 3.5, 4.5]

In [35]:
# matriz
matriz = [[0,0,0,0],[0,0,0,0], [0,0,0,0]]
np.array(matriz)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [36]:
#arreglo con valores igualmente espaciados
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [37]:
a = np.arange(1, 13)

# Tu respuesta aquí
a.reshape(3,4)



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
#valor máximo
np.arange(1, 13)
a.max()

np.int64(12)

In [39]:
#valor mímino
np.arange(1, 13)
a.min()

np.int64(1)

In [40]:
#posición índicel del máximo
#valor máximo
np.arange(1, 13)
a.argmax()

np.int64(11)

**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [41]:
# Tu respuesta aquí
arreglo1 = np.random.randint(1, 20, 5)
print(arreglo1)
arreglo2 = np.random.randint(1, 20, 5)
print(arreglo2)

#suma
suma = arreglo1 + arreglo2
print("Suma:", suma)

#resta
resta = arreglo1 - arreglo2
print("Resta:", resta)

#multiplicación
multiplicacion = arreglo1 * arreglo2
print("Multiplicación:", multiplicacion)

[16  9 10  5 12]
[10  4 12 11 15]
Suma: [26 13 22 16 27]
Resta: [ 6  5 -2 -6 -3]
Multiplicación: [160  36 120  55 180]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [42]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

# Tu respuesta aquí
notas6 = notas[notas >= 6]
print("Notas mayores o iguales a 6:", notas6)

Notas mayores o iguales a 6: [ 8.5  6.   9.2  7.8 10. ]
